# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-13 23:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_geo_db', '0008_auto_20180310_1516'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeographicShape',
            fields=[
                ('geographic_shape_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40, unique=True)),
                ('geocoordinates', models.ManyToManyField(to='django_geo_db.GeoCoordinate')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('geographic_region_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_geo_db.Country')),
                ('geocoordinate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_geo_db.GeoCoordinate')),
            ],
        ),
        migrations.RemoveField(
            model_name='geographicregion',
            name='locations',
        ),
        migrations.DeleteModel(
            name='GeographicRegion',
        ),
        migrations.AddField(
            model_name='location',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_geo_db.Region'),
        ),
        migrations.AlterUniqueTogether(
            name='location',
            unique_together=set([('country', 'state', 'city', 'zipcode', 'geocoordinate'), ('country', 'region')]),
        ),
    ]
