# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-21 16:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('django_geo_db', '0012_auto_20180320_2124'),
    ]

    operations = [
        migrations.RenameField(
            model_name='region',
            old_name='geographic_region_id',
            new_name='region_id',
        ),
    ]
