# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-22 00:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_geo_db', '0014_auto_20180328_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='celeryplottedmaptask',
            name='plotted_map',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='django_geo_db.PlottedMap'),
        ),
        migrations.AlterField(
            model_name='city',
            name='county',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='django_geo_db.County'),
        ),
        migrations.AlterField(
            model_name='city',
            name='geocoordinate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='django_geo_db.GeoCoordinate'),
        ),
        migrations.AlterField(
            model_name='city',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='django_geo_db.State'),
        ),
        migrations.AlterField(
            model_name='country',
            name='continent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='django_geo_db.Continent'),
        ),
        migrations.AlterField(
            model_name='country',
            name='geocoordinate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='django_geo_db.GeoCoordinate'),
        ),
        migrations.AlterField(
            model_name='county',
            name='geocoordinate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='django_geo_db.GeoCoordinate'),
        ),
        migrations.AlterField(
            model_name='county',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='django_geo_db.State'),
        ),
        migrations.AlterField(
            model_name='location',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='django_geo_db.City'),
        ),
        migrations.AlterField(
            model_name='location',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='django_geo_db.Country'),
        ),
        migrations.AlterField(
            model_name='location',
            name='county',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='django_geo_db.County'),
        ),
        migrations.AlterField(
            model_name='location',
            name='geocoordinate',
            field=models.ForeignKey(blank=True, help_text='This is a very specific location.', null=True, on_delete=django.db.models.deletion.PROTECT, to='django_geo_db.GeoCoordinate'),
        ),
        migrations.AlterField(
            model_name='location',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='django_geo_db.Region'),
        ),
        migrations.AlterField(
            model_name='location',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='django_geo_db.State'),
        ),
        migrations.AlterField(
            model_name='location',
            name='zipcode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='django_geo_db.Zipcode'),
        ),
        migrations.AlterField(
            model_name='locationbounds',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='django_geo_db.Location'),
        ),
        migrations.AlterField(
            model_name='locationmap',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='django_geo_db.Location'),
        ),
        migrations.AlterField(
            model_name='locationmap',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='django_geo_db.LocationMapType'),
        ),
        migrations.AlterField(
            model_name='plottedmap',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='django_geo_db.Location'),
        ),
        migrations.AlterField(
            model_name='plottedmap',
            name='location_map_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='django_geo_db.LocationMapType'),
        ),
        migrations.AlterField(
            model_name='region',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='django_geo_db.Country'),
        ),
        migrations.AlterField(
            model_name='region',
            name='geocoordinate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='django_geo_db.GeoCoordinate'),
        ),
        migrations.AlterField(
            model_name='state',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='django_geo_db.Country'),
        ),
        migrations.AlterField(
            model_name='state',
            name='geocoordinate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='django_geo_db.GeoCoordinate'),
        ),
        migrations.AlterField(
            model_name='stateregion',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='django_geo_db.State'),
        ),
        migrations.AlterField(
            model_name='userlocation',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='django_geo_db.Location'),
        ),
        migrations.AlterField(
            model_name='userlocation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='zipcode',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='django_geo_db.City'),
        ),
        migrations.AlterField(
            model_name='zipcode',
            name='geocoordinate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='django_geo_db.GeoCoordinate'),
        ),
    ]
