# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-27 21:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_geo_db', '0016_location_street_address'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='location',
            unique_together=set([('country', 'region'), ('country', 'state', 'city', 'zipcode', 'street_address'), ('country', 'state', 'city', 'zipcode', 'geocoordinate')]),
        ),
    ]
