# Generated by Django 2.1.2 on 2019-06-09 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_geo_db', '0017_auto_20181027_2159'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeographicShapeCoordinate',
            fields=[
                ('geographic_shape_coordinate_id', models.AutoField(primary_key=True, serialize=False)),
                ('order', models.IntegerField()),
                ('geocoordinate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_geo_db.GeoCoordinate')),
            ],
        ),
        migrations.RemoveField(
            model_name='geographicshape',
            name='geocoordinates',
        ),
        migrations.AddField(
            model_name='geographicshapecoordinate',
            name='geographic_shape',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_geo_db.GeographicShape'),
        ),
        migrations.AlterUniqueTogether(
            name='geographicshapecoordinate',
            unique_together={('geographic_shape', 'order')},
        ),
    ]
